### ISSUE TITLE
Start Stop doesn't work

### ISSUE THREAD

**Issue by gimler** [s7anley/redis-sentinel-docker#4]
I can start with `docker-compose up -d` and all works.

But when i stop with `docker-compose stop` and then start `docker-compose start` the sentinel failed.

logs
```
sentinel_1      | *** FATAL CONFIG FILE ERROR ***
sentinel_1      | Reading the configuration file, at line 9
sentinel_1      | >>> 'sentinel known-slave mymaster 192.168.208.2 6379'
sentinel_1      | Wrong hostname or port for slave.
redissentinel_sentinel_1 exited with code 1
```

docker-compose.yml
```
version: '2'

services:
    redis_master:
        image: redis:3.2.9-alpine

    redis_slave:
        image: redis:3.2.9-alpine

    sentinel:
        image: s7anley/redis-sentinel-docker:3.2.9
        environment:
            - MASTER_NAME=mymaster
            - QUORUM=1
            - MASTER=redis_master
            - SLAVES=redis_slave
            - SENTINEL_PORT=26380
        expose:
            - 26380
        depends_on:
            - redis_master
```
