### ISSUE TITLE
/etc/sentinel.conf config error!

### ISSUE THREAD

**Issue by xjzrc** [s7anley/redis-sentinel-docker#8]
![error](https://user-images.githubusercontent.com/24598106/42252968-ff4b8950-7f71-11e8-9834-8786d7529c8e.png)

my docker-compose.yml
```yml
version: '3'

services:
  master:
    image: redis:4.0.10-alpine
    hostname: master
    container_name: master
    network_mode: 'redis_sentinel_net'

  slave_1:
    image: redis:4.0.10-alpine
    hostname: slave_1
    container_name: slave_1
    network_mode: 'redis_sentinel_net'

  slave_2:
    image: redis:4.0.10-alpine
    hostname: slave_2
    container_name: slave_2
    network_mode: 'redis_sentinel_net'
    
  sentinel_1:
    image: s7anley/redis-sentinel-docker:4.0.10
    hostname: sentinel_1
    container_name: sentinel_1
    network_mode: 'redis_sentinel_net'
    ports:
      - 26379:26379
    environment:
      - MASTER_NAME=mymaster
      - QUORUM=2
      - MASTER=master
      - SLAVES=slave_1;slave_2
    depends_on:
      - master

  sentinel_2:
    image: s7anley/redis-sentinel-docker:4.0.10
    hostname: sentinel_2
    container_name: sentinel_2
    network_mode: 'redis_sentinel_net'
    ports:
      - 26380:26379
    environment:
      - MASTER_NAME=mymaster      
      - QUORUM=2
      - MASTER=master
      - SLAVES=slave_1;slave_2
    depends_on:
      - master

  sentinel_3:
    image: s7anley/redis-sentinel-docker:4.0.10
    hostname: sentinel_3
    container_name: sentinel_3
    network_mode: 'redis_sentinel_net'
    ports:
      - 26381:26379
    environment:
      - MASTER_NAME=mymaster      
      - QUORUM=2
      - MASTER=master
      - SLAVES=slave_1;slave_2
    depends_on:
      - master
```

**Comment by s7anley** [comment]
Hi @xjzrc, thank you for pointing out this issue. 

I vaguely remember that the usage of `SLAVES` was added, because of ECS. I need to investigate a little bit more. Meantime, you should avoid using SLAVES configuration and setup slaves correctly e.g.

```yaml
version: '3'

services:
  master:
    image: redis:4.0.10-alpine

  slave_1:
    image: redis:4.0.10-alpine
    command: redis-server --slaveof master 6379
    depends_on:
      - master

  slave_2:
    image: redis:4.0.10-alpine
    command: redis-server --slaveof master 6379
    depends_on:
      - master

  sentinel_1:
    image: s7anley/redis-sentinel-docker:4.0.10
    ports:
      - 26379:26379
    environment:
      - MASTER_NAME=mymaster
      - QUORUM=2
      - MASTER=master
    depends_on:
      - master
```

```
$ docker exec -ti redissentineldocker_sentinel_1_1 redis-cli -p 26379 info sentinel
# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=mymaster,status=ok,address=172.19.0.2:6379,slaves=2,sentinels=1
```
